# toolchain-win32.cmake — LLVM-MinGW cross-compile to Windows x86 (.dll)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_C_COMPILER   i686-w64-mingw32-clang)
set(CMAKE_CXX_COMPILER i686-w64-mingw32-clang++)
set(CMAKE_RC_COMPILER  i686-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Strip any MSVC-only flags that may leak in
string(REGEX REPLACE "/W[0-9]" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
string(REGEX REPLACE "/W[0-9]" "" CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}")
string(REGEX REPLACE "/GS-" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
string(REGEX REPLACE "/GR-" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

set(CMAKE_SHARED_LIBRARY_SUFFIX ".dll")
