name: Build RakNetDLL

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.0.0)"
        required: true

env:
  DIST: dist

jobs:

  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Linux Shared Library
        run: |
          chmod +x build_dll.sh
          ./build_dll.sh linux64

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: dist/linux-x64/libRakNetDLL.so


  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM-MinGW
        run: |
          RELEASE=$(curl -fsSL https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest \
            | python3 -c "import sys,json; print(json.load(sys.stdin)['tag_name'])")

          TARBALL="llvm-mingw-${RELEASE}-ucrt-ubuntu-22.04-x86_64.tar.xz"
          URL="https://github.com/mstorsjo/llvm-mingw/releases/download/${RELEASE}/${TARBALL}"

          curl -fsSL -o /tmp/llvm-mingw.tar.xz "$URL"
          sudo tar -xf /tmp/llvm-mingw.tar.xz -C /opt
          echo "/opt/llvm-mingw-${RELEASE}-ucrt-ubuntu-22.04-x86_64/bin" >> "$GITHUB_PATH"

      - name: Build DLLs
        run: |
          chmod +x build_dll.sh
          ./build_dll.sh win64
          ./build_dll.sh win32
          ./build_dll.sh win-arm64

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: |
            dist/win-x64/RakNetDLL.dll
            dist/win-x32/RakNetDLL.dll
            dist/win-arm64/RakNetDLL.dll


  release:
    needs: [build-linux-x64, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # فقط وقتی tag داریم اجرا شود
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare files
        run: |
          mv artifacts/linux-x64/libRakNetDLL.so artifacts/raknet-linux-x64.so
          mv artifacts/windows-builds/RakNetDLL.dll artifacts/raknet.dll

      - name: Set tag variable
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "RakNetDLL ${{ env.TAG }}"
          files: |
            artifacts/raknet-linux-x64.so
            artifacts/raknet.dll
